apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:Andrey1337/git-ops-example.git
    targetRevision: HEAD
    path: my-chart
    helm:
      valueFiles:
        - values.yaml
        - version-values-test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
