apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Andrey1337/git-ops-example.git
    targetRevision: main
    path: example-subchart
  destination:
    server: https://kubernetes.default.svc
    namespace: quarkus

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
